### ISSUE TITLE
Smoothed profile show 'nan' after datasmooth treatment 

### ISSUE THREAD

**Issue by chua-KY** [zhangqi-chen/pyDiffusion#1]
Hi there, I imported a raw data set in csv format and then perform a datasmooth operation. 
<img width="218" alt="code" src="https://user-images.githubusercontent.com/58806042/70699049-7e579d80-1d03-11ea-857a-45652b1231fb.PNG">

There were 3 phases iterations performed w/o warning or error, and graphs with smoothed data for each phase were shown. However, the plotting of smooth profile is not possible. 

<img width="461" alt="error message" src="https://user-images.githubusercontent.com/58806042/70698570-bad6c980-1d02-11ea-9ed2-9e19a854c1c2.PNG">

When I have a closer look to the smoothed data, I found that the smoothed profile consist 'nan' in resultant profile (X). 

<img width="213" alt="CuSn_sm" src="https://user-images.githubusercontent.com/58806042/70698658-e1950000-1d02-11ea-99ec-ed63908204d5.PNG">

Can anybody help?

**Comment by zhangqi-chen** [comment]
Hi chua, there should be something wrong during data smoothing. Since no data is provided, there are few things I suggest you to check:

1. 'interface' locations should not have composition data in 'profile'. e.g. if there are data points at 20 and 21 microns, the 'interface' should be at 20.5, not 20 or 21.
2. During data smoothing, double check red dots in every figure (phase) after smoothing. If there are no red dots (only blue dots) after smoothing, the smoothed data will be all 'nan', which means smoothing is wrong in the corresponding phase.

Let me know if it helps.

**Comment by chua-KY** [comment]
Hi zhangqi,

Thanks for your feedback. Your solution #1 works!
